export const ADD_TICKET = "PERMISSION_ADD_TICKET";
export const ADD_PROJECT = "PERMISSION_ADD_PROJECT";
export const ADD_MEMBER_TO_PROJECT = "PERMISSION_ADD_MEMBER_TO_PROJECT";
export const ADD_COMMENT = "PERMISSION_ADD_COMMENT";
export const MANAGE_ROLE = "PERMISSION_MANAGE_ROLE";
export const UPDATE_USER_PROFILE = "PERMISSION_UPDATE_USER_PROFILE";